sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root8044

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t8eo4UnCd6ZGWzAU3Pq
    access-key-secret: L2kk5rlHQkHl7HgYSPcqIf84HmSAGF
    bucket-name: take-out-demo27